### PR TITLE
Allows for drawing of bezier curves in RMShape

### PR DESCRIPTION
**Pull request by tmalloy**
Adds the following methods to RMShape:

```
- (void)addCurveToCoordinate:(CLLocationCoordinate2D)coordinate
          controlCoordinate1:(CLLocationCoordinate2D)controlCoordinate1
          controlCoordinate2:(CLLocationCoordinate2D)controlCoordinate2;

- (void)addQuadCurveToCoordinate:(CLLocationCoordinate2D)coordinate
               controlCoordinate:(CLLocationCoordinate2D)controlCoordinate;

- (void)addCurveToProjectedPoint:(RMProjectedPoint)projectedPoint
          controlProjectedPoint1:(RMProjectedPoint)controlProjectedPoint1
          controlProjectedPoint2:(RMProjectedPoint)controlProjectedPoint2;

- (void)addQuadCurveToProjectedPoint:(RMProjectedPoint)projectedPoint
               controlProjectedPoint:(RMProjectedPoint)controlProjectedPoint;
```

Mimicking the existing methods for adding lines and moving to points.

### CODE REVIEW

**Comment by incanus** [comment]
Ooh, nice. I'll try to take a look at this.

**Comment by incanus** [comment]
@tmalloy I got this in support, any ideas here? I haven't used `isnan()` before. We want to keep iOS 5 support for now. 

> In the interests of complete closure.... the 0.5.0 version was failing to compile on anything lower than iOS6.0 because it had isnan() defined as a macro in math.h requiring -ffast-math - only available on iOS6.0 and above. The solution was in the mapbox Xcode project file to set the 'Relax IEEE Compliance' build setting to 'No' rather than 'Yes'.

From http://support.mapbox.com/discussions/mapbox-ios-sdk/551-rmshapes-disappearing-when-partially-on-screen

**Comment by tmalloy** [comment]
Didn't realize that isnan() is iOS 6 only. I'll submit another pull request shortly.

**Comment by incanus** [comment]
Awesome, I appreciate it!

**Comment by tmalloy** [comment]
https://github.com/mapbox/mapbox-ios-sdk/pull/162

**Pull request merged**
