### PR TITLE
Allow custom views for title, subtitle of callout

### PR DESCRIPTION
**Pull request by kylecrum**
SMCallout allows for custom views of the title and subtitle, so I would like to be able to use that functionality as well in order to display images, etc where the subtitle or title might be.

### CODE REVIEW

**Comment by incanus** [comment]
Nice, I'll check this out soon and see how we want to present this and/or manage clamping of frames and the like.

**Comment by kylecrum** [comment]
Ya, currently SMCalloutView doesn't really have any guards against the frame sizes of the custom views, but the views will spill over the callout borders if a developer makes them too large. They have another branch in which the callout is drawn with drawRect, which will theoretically allow arbitrary-sized views inside of the callout, so maybe in the future it will be a bit smarter about it. Right now, I just want to change the font and this seems like the best way.

**Comment by incanus** [comment]
Any forward motion on this? Just curious; I'm leaving the ticket around for whenever anyone can get to it.

**Comment by kylecrum** [comment]
Didn't end up using this functionality in my project, so I didn't get around to doing this. I'll close it for now.

**Pull request closed without merging**
