### PR TITLE
HUD Simplification Feature

### PR DESCRIPTION
**Pull request by MattFoley**
I wanted the ability to hide/unhide views on tap/drag/zoom in order to simplify the controls used to manipulate my map. 

My main branch is drastically different from your release branch, so I pulled out this specific feature into a develop branch to allow you to pull it in if you wanted.

Simple example functionality: 

```
 [_mapView addViewsToHideForSimplify:@[<Some Controls or Views>]];
```

### CODE REVIEW

**Comment by incanus** [comment]
Huh, that's interesting. I'm not sure it's generally useful to our SDK, but I'll leave it open here a while and see if anyone else chimes in. 

Happen to have a video demo of it?

**Comment by MattFoley** [comment]
I don't offhand, but we're pushing for release soon, and creating a decent walkthrough video will end up being a part of that :)

**Comment by MattFoley** [comment]
Hey incanus, you asked for an example of the the HUD simplification I built, and a month later I've finally released the app (with a nod to you guys in the about page). Here it is, https://itunes.apple.com/us/app/mapcraft-world-explorer-for/id591454863?mt=8

You'll see that tapping on the screen will hide and unhide the majority of the HUD. It's a nice to have, but the more I've been playing with it, the more I've been thinking about turning it into a two finger tap.

**Comment by incanus** [comment]
This looks great. One thing I noticed is that the tile loads are pretty slow -- is this my setup, your server, something else, etc.?

**Comment by MattFoley** [comment]
You're right, they do seem slower, it's been on my list to look into. 

We're using a custom tile provider I added to my MapCraft branch in my fork of MapBox, but that shouldn't be causing issues. We started out using Alpstein's fork and that seemed faster, if that helps. I'll definitely be looking into it more soon.

**Comment by MattFoley** [comment]
Did you ever include this into the MapBox framework, or should I close this pull request?

**Comment by incanus** [comment]
Hi @MattFoley. I do appreciate this pull, but I don't think it's mainstream enough for our use. I'm going to close for now but I'm happy to direct people to your fork if it's something they'll need.

**Pull request closed without merging**
