### PR TITLE
Pull request

### PR DESCRIPTION
**Pull request by andreacremaschi**
Hi incanus, here are two commits you could find of some use:
- mbtiles in places other than the main bundle root (addresses: #39)
- fix map max zoom level on devices with retina display (addresses #42)

### CODE REVIEW

**Comment by andreacremaschi** [comment]
@incanus: none of the issues addressed in my pull request is fixed in your commit! A mistake in the fix ref?

**Comment by trasch** [comment]
Could it be that this issue was closed because the commit message mentions a fix for an issue in the Alpstein branch? That would be a GitHub bug then...

This has been fixed upstream btw.

**Comment by incanus** [comment]
Yeah, looks like a GitHub bug. I'll reopen. BTW I'm pulling down Alpstein upstream as of yesterday's 9bc475548ace00082ba8f4597d5a3506c7a0e1bc, which should be integrated into our `develop` shortly (already visible on `develop-refactor` -- taking quite a while to solidify :-)

**Comment by incanus** [comment]
These were absorbed via upstream (Alpstein) merges today into `develop-refactor`. Care to try them out @andreacremaschi?

**Comment by andreacremaschi** [comment]
confirmed working!

**Pull request closed without merging**
