### PR TITLE
disable repositioning of the map when a callout is displayed, in case userTrackingMode is active

### PR DESCRIPTION
**Pull request by meniku**
When callouts for annotations are displayed, MapBox might reposition the map to center the view on the callout. However when the userTrackingMode is set, this results in a buggy placement of the position marker. It doesn't make much sense to center the view on the callout when the tracking is active, because it will move back to the users position almost instantly.

### CODE REVIEW

**Comment by incanus** [comment]
Cool, thanks for this. Makes sense. I'll check out the animation curves, too.

**Comment by meniku** [comment]
i don't know why the animation commit is listed here (573b26a) ? I actually created the pull request before I pushed this commit.

**Comment by incanus** [comment]
If you push to the same branch on your remote, it continues to update the pull request. Sometimes it's a feature :-)

**Comment by meniku** [comment]
oh ok, makes sense somehow ;)

**Comment by meniku** [comment]
could you close this pull-request? I can open another one for a seperate branch.

**Pull request closed without merging**
