### PR TITLE
Newbase - DON'T MERGE YET!

### PR DESCRIPTION
**Pull request by tristen**

### CODE REVIEW

**Comment by incanus** [comment]
This messed up example code indentation somehow. 

http://www.mapbox.com/mapbox-ios-sdk/examples/

**Comment by tristen** [comment]
Hmm - I'll take a look, thanks

**Comment by tristen** [comment]
Should be fixed now

**Comment by incanus** [comment]
I don't have a pre- screenshot handy, but they still don't look right. 
- Should be a linebreak after the `#import` line. 
- Should be a linebreak before the `@end`. 
- Should be more than just strings (`@"…"`) highlighted. Hardly any code is. 
- Weird spottiness, like in [this one](http://www.mapbox.com/mapbox-ios-sdk/examples/drawing-circle/) where 1/3 of a method isn't highlighted and then 2/3 of it are highlighted in a weird turquoise.

**Comment by incanus** [comment]
In fact, all around the color scheme is changed quite a bit. I remember spending some time on this to make it look a lot of like Xcode does natively to feel very comfortable to iOS devs.

**Comment by tristen** [comment]
I can fix the linebreaks. Want to point me to a color scheme example you like?

**Comment by incanus** [comment]
I will see if I can get an old version of what I had before running -- I customized it from the default pygments. My guess is that it referenced the old CSS dynamically though, so I might not be able to.

**Comment by tristen** [comment]
If you could link to the previous code from github that would be great. I can prefix this stuff in pygments for object-c obly rules.

**Comment by tristen** [comment]
Here's a link to pygments from a month old branch in mapbox.com. https://github.com/mapbox/mapbox.github.com/blob/firstlook/_includes/css/pygments.css#L1-L63 Is this where you made customizations?

**Comment by incanus** [comment]
Thanks for checking this out btw! 

https://github.com/mapbox/mapbox-ios-sdk/commit/976ca3ad8fd90c2cf9aa32ff3a765a02a213dda1
https://github.com/mapbox/mapbox-ios-sdk/commit/529f8457bc1f77b163d5b699f2d18a85c9b6cc20

**Comment by tristen** [comment]
Alright, this is by no means an elegant solution but for now I've added code highlighting rules specific to objective-c in the this repository. Should/might circle back on this.

**Comment by incanus** [comment]
Hmm, it's still being weird with multiple arguments where it wasn't before. Example: 

```
NSDictionary *json = [NSJSONSerialization JSONObjectWithData:[[NSData alloc] initWithContentsOfFile:jsonPath]
                                                     options:0
                                                       error:nil];
```

http://www.mapbox.com/mapbox-ios-sdk/examples/drawing-geojson-shape/

Check out how the three arguments get different coloring.

**Comment by incanus** [comment]
This appears to be affecting the API docs as well. 

http://www.mapbox.com/mapbox-ios-sdk/api/

Previously the many bits in between `<code>` tags had rendered in color and gave both a fresher look and an Xcode-like appeal to the (long) docs. Now it's a lot of gray.

**Comment by incanus** [comment]
Is there an easy way I can revert this? I'm expecting probably our highest traffic of the year on the iOS stuff in the next week or two.

**Comment by yhahn** [comment]
No, not easy to revert. @tristen let's pause other things if we need to to get this resolved for justin.

**Comment by tristen** [comment]
We good here @incanus ? Let's cut any further issues into separate tickets

**Comment by incanus** [comment]
No, same issues persist. 
- In the [API docs](http://www.mapbox.com/mapbox-ios-sdk/api/), things like `property` are no longer in color. 
- In examples like [this one](http://www.mapbox.com/mapbox-ios-sdk/examples/drawing-geojson-shape/), highlighting is very muted and still incorrect for methods with multiple arguments (most of them). For example, in this: 

screen shot 2013-09-11 at 9 29 25 am

  Note how `JSONObjectWithData:` is not highlighted whereas `options:` and `error:` are, plus none of the rest of the method has any color to it.

**Comment by yhahn** [comment]
@incanus I took a look at this this weekend by setting up an [old version](https://github.com/mapbox/mapbox-ios-sdk/commit/9628fc8c0231a886960fc74cffd7cdcc48d11f4e) of the repo and mapbox.com CSS for it to point at. As far as I can see there are no major differences with syntax highlighitng between the revision I looked at and the current.

I also took a look at the markup that pygments generates and it looks like there just isn't much more granularity possible based on what it generates currently. Other repositories using standard github highlighting (pygments) appear to suffer from the same issues (https://github.com/mruegenberg/ios-linechart#usage).

I found one mention of switching highlighting to `smalltalk` for more colors but it appears to me that this approach introduces some errors/bad highlighting into the mix.
- http://stackoverflow.com/questions/11890864/is-there-a-github-markdown-language-identifier-for-objective-c-code/11890935#11890935

---

At 9628fc8c0231a886960fc74cffd7cdcc48d11f4e
sdk-9628fc8c0231a886960fc74cffd7cdcc48d11f4e

Current gh-pages
sdk-master

**Comment by incanus** [comment]
Thanks for taking a look, @yhahn. It's quite possible I'm misremembering, but man, I just don't remember the odd argument bit, at the very least (that's the thing about misremembering, though…) And I definitely feel like I tweaked a number of colors to give it some nice looking variables. 

@tristen added a commit or two last week that helped with my first point above (_property_ et al. in the API docs), so let's call this done. If I get a chance to improve this somehow, I will.

**Comment by yhahn** [comment]
y it sounds like `objective-c` highlighting in pygments/github needs love overall. Sidequest?

**Pull request merged**
