### PR TITLE
Fix for #433

### PR DESCRIPTION
**Pull request by farfromrefug**
This fixes sources from blocking each other, see https://github.com/mapbox/mapbox-ios-sdk/issues/433
The fix is combination of different fixes to make sure no source ever block another.

### CODE REVIEW

**Comment by mohpor** [comment]
Have you extensively tested it yet? I'm suffering form the #433 as well and I hope this fix is merged asap.

**Comment by farfromrefug** [comment]
I have tested on my device with the Network Link Conditioner. I can't say i heavily tested it :D
But in my case it solved the problem. And seeing what has been fixed i am almost sure it is going to fix it for you ;)

**Comment by mohpor** [comment]
That's a relief!
This might solve the #405 too. I'm not sure, but my guess is, it will.

**Comment by farfromrefug** [comment]
Ok so still working on this one as i am seeing other behaviours after that change.
One question: with my chnage (i mean in my branch), when zooming out it does not keep the drawing of old tile while waiting to get them, they all go back to the loading tile.
Do you see that in the master branch? (it seems like you should see the same behaviour).
@mohpor can you help on this?
I can't go back to the master branch anymore to many changes, my app won't build

**Comment by mohpor** [comment]
@farfromrefug , I'm not using your branch right now. Can you elaborate on what you mean? I'm not sure I understand the problem. I can always create test projects based on your branch.

**Comment by farfromrefug** [comment]
So this is what i see:
- try to start with the cache cleared
- zoom to a high level
- move to a point where you know you dont have cached tiles for lower zooms
- zoom out
  While zooming out how does it behave?
  for me it zooms out correctly but as soon as it arrives to the target zoom there is a redraw and there instead of keeping the higher level tiles waiting for the new ones, it draws the loading tile (grid)

**Comment by farfromrefug** [comment]
So i have been working again a lot on this
I decided to refacor RMMapTiledLayerView. The idea was:
- better separation of drawing and image request
- using NSOperationQueue instead of dispatch_async
  For now i chose to limit the queue to 10 concurrent requests. Does it make sense?
  A lot of things are going better for me with this

Also i want to point out what i discovered working on this. There are some bugs in CATiledLayer on ios 7. look [here](https://github.com/Cocoanetics/RadarSamples).
It seems to be fixed in 7.1 which i am not on :s

**Pull request closed without merging**
