### PR TITLE
iOS 7 support

### PR DESCRIPTION
**Pull request by incanus**
This is the nearly-complete iOS 7 support for the SDK. There are some small remaining items, detailed below. 
### Changes
- iOS 7-style user location dot, `RMUserTrackingBarButtonItem`, and callouts. 
- Global `tintColor` support, including dimming. 
- `RMPointAnnotation` markers now also follow the `mapView.tintColor`. 
- Change page curl transition to either a translucent, slide-up modal (iPhone) or a popover (iPad) for attribution info. 
- Added an activity indicator when loading the attribution content `UIWebView`. 
- Updated background grid view behind loading tiles to look better. 
- Support for top and bottom `UIViewController` layout guides. 
- Added tappable compass image during map rotation. 
- Fixed a bug with requesting MapBox `RMMarker` objects tinted with colors in non-RGB color spaces. 
- Now requires Xcode 5.0+ for access to iOS 7 SDK. 
### Remaining
- [x] Animation of `RMUserTrackingBarButtonItem` background color shouldn't happen. 
- [x] User location dot doesn't pulse. 
- [x] User heading accuracy wedge still showing iOS 6 style; needs to be a tinted gradient. 
- [ ] Need to build out a distance scale view for when the user is zooming. 
- [x] Slight bug in attribution modal on iPhone during device rotation. (https://devforums.apple.com/message/873505) 
- [ ] Callouts can occasionally appear under the navigation bar. (https://github.com/nfarina/calloutview/pull/52)
- [ ] Callout appearance animation needs tweaks. (https://github.com/nfarina/calloutview/pull/52)
- [x] User location dot shadow could use some very minor tweaks. 
- [x] Slight jiggle in compass rotation (due to constraints?)
- [x] Bundle 64-bit build of `libProj4.a`. 
- [x] Enable 64-bit simulator testing. (https://github.com/groue/GRMustache/issues/64)

### CODE REVIEW

**Comment by GameFanager** [comment]
Cloned the commits you made, and still getting ld: symbol(s) not found for architecture x86_64 errors

**Comment by incanus** [comment]
@AniMud: Yes, I need to rebuild `libProj4` for 64-bit. In the meantime, you can add the Proj4 sub-project to your workspace and build it yourself instead of using the provided library.

**Comment by incanus** [comment]
Need to consider responder chain traversal for the `topLayoutGuide` stuff per @johnclayton.

**Comment by incanus** [comment]
@AniMud: you are still going to see these for a bit if you are testing 64-bit builds in the simulator since this runs as 64-bit _desktop_ and per https://github.com/groue/GRMustache/issues/64 not all our sub-libs have that slice yet. However, running on a 64-bit test device (i.e. iPhone 5s) should work ok.

**Comment by groue** [comment]
Hi guys! Just to let you know, groue/GRMustache#64 is fixed in v6.8.3: libGRMustache6-iOS.a now contains both x86_64 and arm64 slices.

**Comment by incanus** [comment]
Going to merge this into `develop` finally -- it's time.

**Pull request merged**
