### PR TITLE
Fix crash with hidden logo bug

### PR DESCRIPTION
**Pull request by soffes**
Autolayout freaks out if it tries to layout a hidden logo bug. This is easily fixed by checking the logo bug is not nil and should be shown

### CODE REVIEW

**Comment by bradfol** [comment]
+1 nice find on this one

**Comment by tmcw** [comment]
@incanus should this get merged?

**Comment by RyanCopley** [comment]
Yes

**Comment by incanus** [comment]
This is obsoleted by the fixes in 2e920b139857594f8e7476bc39edcc333209457a and fd21d75. Thanks for highlighting the issue though.

**Pull request closed without merging**
