### PR TITLE
Check if annotation isn't nil before adding to array & tapOnLabelForAnnotation

### PR DESCRIPTION
**Pull request by maciekish**
If we set constraints for the map using setConstraintsSouthWest, enable showsUserLocation and then launch the app outside of the constraints it will crash while trying to add a nil annotation.

Besides it's always a good idea to check for nil when adding something to an array/dictionary.

### CODE REVIEW

**Comment by maciekish** [comment]
Also added a fix for https://github.com/mapbox/mapbox-ios-sdk/issues/440#issuecomment-50644786

**Comment by incanus** [comment]
I'm curious in 1954683 about the implications of possibly not adding an annotation (if `nil`) to the main array, but still adding it to the quad tree. Any ideas on behavior there @maciekish? I haven't checked it out yet.

**Comment by maciekish** [comment]
Seems like i missed that, fixed it now.

**Comment by maciekish** [comment]
Hi, any idea when you can have a look at this? The tapOnLabelForAnnotation issue is pain.

**Comment by incanus** [comment]
Whoops, will look soon. Did a big ticket sweep yesterday but forgot that PR's didn't show up there.

**Pull request closed without merging**
