### PR TITLE
Added storyboard / xib support

### PR DESCRIPTION
**Pull request by RyanCopley**
Currently it's not very feasible to use storyboards or xibs with RMMapView because there is no initWithCoder function.

### CODE REVIEW

**Comment by RyanCopley** [comment]
I've added a handful of other small fixes, also. Not sure if you want to accept them all, but I recommend 3936795 and 737d422

**Comment by incanus** [comment]
It's true that `-initWithCoder:` isn't overridden, but `super`'s implementation is indeed taken into account, e.g. https://github.com/mapbox/mapbox-ios-sdk/blob/fb8a9e25ca699b378fc22457820598d19709a5b0/MapView/Map/RMMapView.m#L612-L620

**Comment by RyanCopley** [comment]
I don't send pull requests because I see methods missing... I did the pull request because the super's version of initWithCoder is not the same as what I have done. If you do it with the super version, you cannot remove the default map and replace it with your own tile source.  It's being used in a project at work and I'm currently at home so I don't have access to my implementation, but the super version is not 1:1.

**Comment by incanus** [comment]
I did check out the code. I see a call to `super`, then a: 

```
 return [self initWithFrame: [self frame] andTilesource:[RMMapboxSource new]];
```

Which just uses a default `mapID` like some of the other initializers do. I'm not sure how this could change the behavior or later setting a custom `mapID`. 

BTW I do appreciate the code; I just want to make sure this is needed.

**Comment by RyanCopley** [comment]
Actually, I forgot this project is on GitHub. Here is what I was doing:

```
RMBingSource* bingMap = [[RMBingSource alloc] initWithMapsKey: bingKey];
RMInrixTrafficSource* inrixTraffic = [[RMInrixTrafficSource alloc] initWithMapsKey: inrixDevicetoken];
[mapView removeTileSourceAtIndex:0];
[mapView addTileSource:bingMap];
[mapView addTileSource:inrixTraffic];
```

Without the initWithCoder: overriden, the default map is unable to be removed. Since you can't (in an intuitive way) swap out which map source you want with a storyboard UI element, it adds the default. For some odd reason, without this patch, you cannot do RMMapView -removeTileSourceAtIndex, or even add a new source for that matter. I checked to make sure mapView isn't nil, and it even would display fine. Once I added the initWithCoder with a proper override, everything worked as expected.

**Comment by RyanCopley** [comment]
Also, I created an Inrix map tile data source. They're a bit pricy, but they're one of the better providers. Would you like me to submit this as a different PR?

**Comment by incanus** [comment]
Interesting. I would recommend you actually do `mapView.tileSource = ...` to set the first one, but regardless this sounds like it's worth looking into to get at the root cause. Even with the default, there should always be something at index `0`, though you shouldn't be able to remove the only tile source being used IMHO.

**Comment by incanus** [comment]
I'd say the Inrix source should go up to Alpstein directly.

**Comment by RyanCopley** [comment]
I think it's because layoutSubviews isn't called early enough. Also, what is "Alpstein" ?

Edit: Oh. Main project. Got it

**Comment by incanus** [comment]
Bit more info re: Alpstein vs. here that I just added at fb8a9e25ca699b378fc22457820598d19709a5b0

**Comment by RyanCopley** [comment]
I'll send the PR to them tomorrow once I get back in the office. I still stand that either my PR should be accepted or the root cause should be fixed in this, I prefer to pull from cocoapods directly rather than specifying my repository because of this patch. -initWithCoder isn't that bulky ;)

**Comment by RyanCopley** [comment]
Also, the -removeTileSourceAtIndex can be moved to a different spot arbitrarily, no real reason why I removed it first before adding the ones I want.

**Comment by RyanCopley** [comment]
Also, I believe I also tried 

```
  mapView.tileSources = @[bingMap, inrixMap];
```

and that still failed while using storyboards

**Comment by RyanCopley** [comment]
You should be asserting that a map source exists here: https://github.com/mapbox/mapbox-ios-sdk/blob/fb8a9e25ca699b378fc22457820598d19709a5b0/MapView/Map/RMMapView.m#L612-L620 rather than adding one if it doesn't exist.

Adding one on-the-fly is problematic by design

**Pull request closed without merging**
