### PR TITLE
OpenMapSurfer map tiles source added.

### PR DESCRIPTION
**Pull request by MrZoidberg**
Hi,

I've added OpenMapSurfer tiles source http://www.openmapsurfer.uni-hd.de/. It's based on OSM data, but imho with much better rendering. Also they have ASTER GDEM & SRTM Hillshade and other layers, but I didn't added them.

### CODE REVIEW

**Comment by tmcw** [comment]
Shouldn't extra contrib layers be just used by adding a new XYZ tile URL, rather than a new class?

**Comment by MrZoidberg** [comment]
I'm sorry, what do mean?

**Comment by tmcw** [comment]
Like, at least in the land of web mapping, there's a general layer type, like `L.tileLayer`, and then individual applications will create versions of this, like `L.tileLayer('http://openmapsurfer.uni-hd.de/tiles/roads/x={x}&y={y}&z={z}')` - this way the client, like Leaflet or OpenLayers doesn't have hundreds of definitions for the many tile servers of the internet, but instead this is just something where people instantiate an abstract tile layer class with the necessary details, in their application.

**Comment by MrZoidberg** [comment]
Maybe I'm wrong, but this is how other tile source are done in the Mapbox iOS SDK. E.g. like in https://github.com/mapbox/mapbox-ios-sdk/blob/release/MapView/Map/RMMapQuestOSMSource.m.

**Comment by incanus** [comment]
Right, needs a tile cache unique key, min/max zoom callbacks or defines in the class, `isCacheable`, etc. per the [`RMTileSource`](https://github.com/mapbox/mapbox-ios-sdk/blob/release/MapView/Map/RMTileSource.h) protocol. For very generic `z/x/y` sources [`RMGenericTileSource`](https://github.com/mapbox/mapbox-ios-sdk/blob/release/MapView/Map/RMGenericMapSource.h) can be used but a specific one is preferred for best use alongside other layers.

**Comment by incanus** [comment]
It seems like you _could_ just use `RMGenericTileSource` @MrZoidberg for this simple use case. Stuff like [`RMBingSource`](https://github.com/mapbox/mapbox-ios-sdk/blob/release/MapView/Map/RMBingSource.h) got its own class owing to "unique" tile retrieval requirements. Closing here.

**Pull request closed without merging**
