### PR TITLE
Fix for setLayer disappearing annotations

### PR DESCRIPTION
**Pull request by tracyharton**
Added refreshLayer to update changed annotation from delegate

### CODE REVIEW

**Comment by incanus** [comment]
Hi @tracyharton, thanks for the patch. What exactly is the problem that is being solved here?

**Comment by tracyharton** [comment]
Currently, setLayer removes the layer from the overlay view, changes annotation.layer to the new layer, but does not add the new layer back to the overlay view.  Since that is currently taken care of by RMMapView:addAnnotation, the annotation effectively disappears.  

The patch basically  just adds the new layer back to the superview.

The added refreshLayer just calls setLayer with the annotation's delegate layerForAnnotation.  Useful if you change the underlying layerForAnnotation behavior and need to refresh any on-screen annotations.

**Comment by jokeruzzo** [comment]
hi , tracy when you need to call refresh layer in your patch ?
I've try to implement it...but not work for me....layer disappear.

thank's for your reply.

**Comment by incanus** [comment]
@tracyharton, I took the `superlayer` fix -- thanks for that. I'm going to pass on the `refreshLayer` for now, though. 

Also, just a side note, if you make a specific branch for pulls, you won't get the ongoing commits like in this pull request. If you just use the branch for submitting the pull request and don't push any other commits to it, it will not grow like this.

**Comment by tracyharton** [comment]
Yea, I figured that out after I submitted a few...   After talking with you, I was going to push them up to alpstein individually, but hadn't gotten to it yet.      I had incorrectly assumed that git/github would only reference the commit on the screen, not the entire branch, when doing a pull-req...

I think the refreshLayer needs a check to see if the RMAnnotation is currently visible before forcing a reload of the layer, but without the general functionality there is no way to change annotations (images or sizes or shapes) unless the user pans off screen and back again.  I use refreshLayer all over the place in a few apps that have dynamic annotations.

**Pull request closed without merging**
