### PR TITLE
Updating iOS SDK docs

### PR DESCRIPTION
**Pull request by tatsvc**
@katydecorah I added css for both a light and a dark iphone frame:

The setup for an image looks like this now:

```
<div class='pad4 fill-light clearfix'>
  <div class='device device-phone-h contain'>
      <img src="{{site.baseurl}}/images{{page.url | replace:'examples/',''}}.png" />
     <div class='device-details'></div>
   </div>
</div>
```

screen shot 2015-03-20 at 11 22 51 am

You can make a device white by adding the `.device-white` class:

```
<div class='pad4 fill-light clearfix'>
  <div class='device device-phone-h device-white contain'>
      <img src="{{site.baseurl}}/images{{page.url | replace:'examples/',''}}.png" />
     <div class='device-details'></div>
   </div>
</div>
```

screen shot 2015-03-20 at 11 23 05 am

If you would need a vertical device you can change `.device-phone-h` to `.device-phone-v`

### CODE REVIEW

**Comment by katydecorah** [comment]
@tatsvc awesome! I just added logic so those new classes are applied based on a page's front matter.

For example, by default all examples will be dark and horizontal.
- If you add: `device: white` to a page's front matter, then you'll get the white frame.
- If you add `rotation: vertical` to a page's front matter, then you'll get a vertical frame.

Likewise, you can add `device: white` and `rotation: vertical` in the front matter to get a white _and_ vertical frame.

**Comment by katydecorah** [comment]
Just noting ideas for new examples:
- Handling rotation
- Specifying center and zoom level

**Comment by tatsvc** [comment]
> Handling rotation
> Specifying center and zoom level

Shouldn't this be in the first example? Because this is something you will probably need for every map?

**Comment by katydecorah** [comment]
@tatsvc that's a good point! Without the rotation and center/zoom level, the example images don't reflect the code. We should make sure these sync up.

**Comment by katydecorah** [comment]
Tracking progress:
- [x] A simple map view
- [x] **new** Handling rotation 
- [x] Custom style
- [x] Layered styles
- [x] Drawing a Mapbox marker
- [x] Custom image and color on Mapbox marker
- [x] Custom image marker
- [x] Clustering points
- [x] **new** Clustering points and centering labels
- [x] Custom accessory view in a marker callout
- [x] Drawing a shape
- [x] Drawing a circle
- [x] Drawing a GeoJSON-based line
- [x] **new** Drawing a GeoJSON-based shape
- [x] Converting points

### To do
- [x] Make devices look good on mobile as well

**Comment by tatsvc** [comment]
### Up next:
- [x] @katydecorah checks all comments for typos / adds comments 
- [ ] @tatsvc tests all projects to make sure nothing went wrong from copy/pasting to sublime

**Comment by tatsvc** [comment]
Final check:
- [x] A simple map view
- [x] Handling rotation
- [x] Custom style
- [x] Layered styles
- [x] Drawing a Mapbox marker
- [x] Custom icon and color on Mapbox marker
- [x] Custom image marker
- [x] Clustering points
- [x] Clustering points and centering labels
- [x] Custom accessory view in a marker callout
- [x] Drawing a shape
- [x] Drawing a circle
- [x] Drawing a GeoJSON line
- [x] Drawing a GeoJSON shape
- [x] Converting points

**Comment by incanus** [comment]
:heart_eyes: :heart_eyes: :heart_eyes:

**Pull request merged**
