### PR TITLE
Docq

### PR DESCRIPTION
**Pull request by tristen**
This commit:
- Updates the layout to match new documentation structure
- Drops `api/` and redirects to API overview with actions to read documentation from xcode
### Landing

screen shot 2014-03-04 at 11 42 15 am
### Examples

screen shot 2014-03-04 at 11 41 51 am

cc @incanus

### CODE REVIEW

**Comment by incanus** [comment]
This is looking great @tristen. Quick feedback: 
- Per chat I do think real landscape device chrome would be better for the examples. However a) these need updated to a 4" tall device anyway (iPhone 5+) and b) maybe we need a light system for auto-wrapping imagery with chrome, ideally retina imagery that we capture from device or simulator (which can do retina w/o a retina Mac). 
- Love the default page header (the dark one) but the hard edges on some of the screenshots look weird. 
- **Love** the collapsed install stuff. The live version is lengthy and probably intimidating. 
- I feel like the version tag should be a) more prominent and b) do something, even if just linking to the repo. I know we have _open source_ just above that but I want to make clear that it's on GitHub right now. Even if this is added by a "fork me" ribbon or something. 
- The _For Full API documentation check out the embedded Xcode Atom feed_ is too slim and people won't know what the Atom part means, even if they know Atom. I will patch this up now. Some sort of inline imagery based on what I pasted in chat yesterday would be good here, e.g. a contextual popup in Xcode.

**Comment by incanus** [comment]
> I feel like the version tag should be a) more prominent and b) do something, even if just linking to the repo. I know we have open source just above that but I want to make clear that it's on GitHub right now. Even if this is added by a "fork me" ribbon or something.

Did this in f7c7a03, but got any styling ideas?

**Comment by incanus** [comment]
Here are a slew of chrome options, reflection highlights, and status bars gleaned from [Screentaker](http://fabian-kreiser.com/screentaker/), which is what I usually use for these sorts of things: 

https://www.dropbox.com/sh/ihqhddnwxgww1pf/CFIt7QXc8r

**Comment by incanus** [comment]
Here's the chat image from before that probably best represents the built-in docs: 



_Full contextual help for all API is available right in Xcode, either inline or Xcode's documentation viewer_

**Comment by incanus** [comment]
Three shots as 4" retina landscape: 
- [Mapbox iOS Example](https://f.cloud.github.com/assets/17722/2325688/ec2e1da2-a3d8-11e3-8fa9-5be71209aff1.png)
- [Mapbox Me](https://f.cloud.github.com/assets/17722/2325692/fd79ee56-a3d8-11e3-807c-dc8c5a601b96.PNG)
- [Weekend Picks](https://f.cloud.github.com/assets/17722/2325698/0b507234-a3d9-11e3-84f0-1c32c406538c.png)

**Comment by incanus** [comment]
Still not seeing search working right here. Generally I don't get anything, and when I do get a result, it's always this: 

screen shot 2014-03-10 at 10 04 30 am

**Comment by tristen** [comment]
Hrm so searching examples works for me:

screen shot 2014-03-10 at 1 13 16 pm

but Swiftype seems to be limited to searching physical pages and not anchor links in a doc.

**Comment by incanus** [comment]
So all of the info we have in the guides currently, especially how to do offline stuff, doesn't come up in search. Also, search is not too useful on those front pages, and doesn't cross-index to the examples. Is there a way to do that? (search examples from a non-example page)

Given that we're trying to can the guides, let's sit on this for a bit, but we should be aware of it. /cc @geografa

**Comment by incanus** [comment]
P.S. Cache clear fixed searching on examples from the main page. Given that we're deprecating guides and favoring examples, we can consider this thread closed.

**Pull request merged**
