### PR TITLE
Maply

### PR DESCRIPTION
**Pull request by mousebird**
I'd leave this one in its own branch for now.

### CODE REVIEW

**Comment by mousebird** [comment]
I've compared Maply and route-me tile sources and I think I have a handle on why the Maply ones are faster.

For local MBTiles:
- route-me is using a single queue in FMDB to access the tiles.
- Maply is hitting the sqlite database at a lower level on multiple threads.

The Maply solution apparently works because I'm only reading, not writing.

For remote tiles:
- route-me is caching to a local sqlite database via FMDB.  In particular, caching the images themselves so the database.
- Maply is writing to a directory on the file system on multiple threads.  There's no locking associated with the central database.

Maply is, to be fair, kind of doing a half assed job of caching there.  I've seen better hybrid solutions where the tiles are stored in the file system, but there's a sqlite database managing them.

So to read at the same speeds we're seeing in MapBox Earth (from WhirlyGlobe-Maply) we'd need to make some modifications to the route-me tiles sources and caching system.

**Comment by incanus** [comment]
Cool. I'm going to check out a couple things, in progression: 
- `FMDatabasePool` for multithreaded reads
- Multiple `FMDatabase` objects for reads
- Straight SQLite, probably from `MBTileQuadSource.mm`

**Comment by incanus** [comment]
Sorry, I should clarify. I am seeing Maply being slower for local MBTiles. I'm not sure yet if it's a SQLite thing or what, but figured I'd try to some low-hanging fruit first.

**Comment by mousebird** [comment]
You mean route-me + Maply, right?

**Comment by incanus** [comment]
Yeah, sorry. Going through `RMMBTilesSource` using Maply.

**Comment by incanus** [comment]
So not too much luck here. On a whim, I commented out all of the SQLite code in `RMMBTilesSource` and just returned static values and a static tile image. See https://gist.github.com/incanus/a7ff455522db38cfa3f1#file-gistfile1-m-L92

Still renders pretty slowly. 

Is there an easy way for me to switch between Maply and Route-Me tile sources and not just rendering mode?

**Comment by mousebird** [comment]
Right now, no.  I'll hook up a pure Maply tab early tomorrow and we'll try that out.

**Comment by incanus** [comment]
In https://github.com/mousebird/mapbox-ios-sdk/commit/1be3fa232efa4aebfbc7fca2b5dde69fc0110409 I'm looking for WhirlyGlobe 95b8536b48e771903ab49218c9c9e46208c57594 -- have you pushed that anyplace?

**Comment by mousebird** [comment]
Pushed.  Too many subprojects, sorry.

**Comment by incanus** [comment]
Sweet, that looks good. 

I'll keep plugging at the performance stuff. As I see it, we have a couple other things still: 
- [ ] Animated zooms on gestures
- [ ] Still some minor annotation jitter

**Comment by mousebird** [comment]
Did you see the shape comparison tab?  I think that makes a nice test case.

I can probably get the animated zoom working in the next couple of days.  The annotation jitter might go into next week.

**Comment by incanus** [comment]
Ah, I wasn't tracking https://github.com/mousebird/mapbox-ios-example/tree/maply yet, will do.

**Comment by mousebird** [comment]
I've added a separate set of tests for Maply only.  It's interesting how much of this is perceptual.
At this point I think the Maply and route-me MBTiles loaders are pretty similar.  The main difference is that Maply loads intermediate levels.
The network data sources seem to be different, though.  I think the Maply version is faster than route-me.  My guess is the cache on that.

**Comment by incanus** [comment]
It could be perceptual, yeah. Sort of like the async hack I have in our develop branch for intermediate levels for remote tiles.

**Comment by mousebird** [comment]
Now that I can compare them in the same app I think the local MBTiles example is a no-op.  Bit of a wild goose chase there, I'm afraid.

I see a pretty clear difference in remote tile loading, though.  Both in the way intermediate levels load, which we can't really change for route-me and some delay, which we probably could change.

Then there's the Shape layer, which is a very simple example of improvement.

So the question is, where do we want to go with this?  I've got a couple bugs to fix, but we're basically there with Maply integration.

**Comment by mousebird** [comment]
I've added the double tap (and two finger tap) zoom animation to the Maply variant and fixed a startup problem.
I think this one's in pretty good shape.

**Comment by incanus** [comment]
I'm missing `libjson.h` to build in the latest commits.

**Comment by incanus** [comment]
Still seeing some annotation pan jitter; any ideas?

**Comment by incanus** [comment]
I'm curious if anyone else is using this or trying this branch out.

**Comment by RubioV** [comment]
Justin, I'm following this with interest, but I have yet to try it out, will do so pretty soon. The problem I have with the plain MapBox SDK right now is that I need to be able to handle 400+ markers on my map. This is pretty slow right now and some quick profiling is showing me it is simply due to Quartz rendering in MapBox. Maply rendering of shapes/markers should be much faster. So I'm trying to decide if I'm going to try out this branch or switch over to Maply entirely. The point is, I really like MapBox for other features, such as background caching etc (which I've been working to improve)...

**Comment by incanus** [comment]
@RubioV: there are some loose plans to render markers/overlays in Maply (i.e., OpenGL) at some point if there's enough interest. But currently, this branch just uses Maply for tile rendering and still uses Quartz for the markers/overlays.

**Comment by mousebird** [comment]
You can use the Maply markers directly if you're in Maply mode with the route-me view controller.  That's probably the simplest approach.  The way route-me represents markers is always going to be a bit expensive.

We did hook up the tile data sources that route-me provides, so you can use WhirlyGlobe-Maply with those as well.  That means you can do route-me with Maply or WhirlyGlobe-Maply with route-me tile sources.

**Comment by incanus** [comment]
Good points, @mousebird!

**Comment by RubioV** [comment]
@mousebird @incanus Thanks for the help guys. I wasn't aware that I can use Maply markers when in Maply mode. I will be running some tests to determine if I'll be using route-me/MapBox, Maply, or the hybrid solution in this branch. I'll post here if I have any more information to share.

**Comment by mousebird** [comment]
I've updated the Maply branch to use a static version of WhirlyGlobe-Maply.  This one also has a fix for ios7, though it was nothing serious.

You'll need updates to both the mapbox-ios-sdk and the example app.  The whole submodule thing is confused when working with my copy vs. yours, but if you put them all together again it works.

**Comment by incanus** [comment]
Sweet, I'll check this out. I've got my own iOS 7 changes incoming soon, but most are NDA due to API used.

**Comment by mousebird** [comment]
Oh yes I imagine.  None of that sort of thing.  These were just compile errors with Xcode5.

**Comment by mousebird** [comment]
So, to summarize this effort.  It works, you can use Maply as your underlying base map and you can access Maply's other features, like vectors labels, markers and such.  You can also use the MapBox SDK's overlay features, annotations and so forth.

As a side effect, you can now go the other way.  You can use MapBox SDK (route-me) tile sources in WhirlyGlobe-Maply.

The base map display is not reliably faster than route-me, which is odd.  The tile sources might be the culprit or it might be the interaction between Maply and the UIScrollView.  MapBox Earth is visibly faster, so that's a bit of a head scratcher.  I'll be doing some work to update tile loading speed in WhirlyGlobe soon for a client, so we might want to revisit this in Maply 2.3.

At this point I'd say the Maply branch is most useful if you want access to Maply features, but have a significant investment in the MapBox/route-me SDK.

**Comment by incanus** [comment]
This sounds about right. Interested to see the possible performance stuff later on. I think after the iOS 7 dust settles, I'd like to get this made into a binary framework version for folks to more easily play with.

**Pull request closed without merging**
