### PR TITLE
Annotation movements synchronised with zooms

### PR DESCRIPTION
**Pull request by sobri909**
Changes relevant to #116.

No idea why the pull request is showing a massive list of old commits (I appear to be cursed with constant git fumbles). The "files changed" is showing the right things though. 

The only changes are a slightly modified `setZoom:atCoordinate:animated:` and a new custom `zoomToRect:animated:`

### CODE REVIEW

**Comment by macawm** [comment]
I found this patch buggy. It breaks zoom event handling mainly.

**Comment by sobri909** [comment]
@macawm I haven't noticed any zoom event problems yet. Any specific cases?

**Comment by macawm** [comment]
I would never get beforeMapZoom or afterMapZoom calls for a double click event. It seemed as though the zoomDelegateQueue of RMMapView was continually left in a bad state, i.e. was suspended with an operation pending.

**Comment by sobri909** [comment]
Ah yeah, looking at the diff I see it now. I'm actually explicitly using an `_ignoreZoomEvent` flag. When really the only thing that needs to be sidestepped (I think) is the `correctPositionOfAllAnnotationsIncludingInvisibles:animated:` calls, as those are the ones that mess with the positioning during zoom.

**Comment by morgz** [comment]
Did you guys reach a conclusion on this? I'd love to have annotation animations in sync with animated map zoom..

**Comment by sobri909** [comment]
I'll be revisiting this sometime over the next week or two, as I'm seeing similar out-of-sync annotation movements during rotation, which will probably require a similar fix. When I get to doing that I'll fix up the missing zoom events.

**Comment by wprater** [comment]
Im experiencing this same issue.  When using `setZoom:atCoordinate:animated:` the markers/annotation are not zooming in sync.  

Is there a proposed fix for this @incanus ?

**Comment by incanus** [comment]
Sorry for the delay on this. 

> I'll be revisiting this sometime over the next week or two, as I'm seeing similar out-of-sync annotation movements during rotation, which will probably require a similar fix. When I get to doing that I'll fix up the missing zoom events.

@sobri909 any movement on this on your end?

**Comment by wprater** [comment]
Not sure if this is related, but Im also seeing the current user annotation appear when I `setZoom:atCoordinate:animated` to a location where its definitely not at.  As soon as I zoom out a slight bit, it disappears.

**Comment by sobri909** [comment]
@incanus Can't recall how we worked around that one in the end. Pretty sure we didn't fix the broken zoom events. Our fork has fallen far behind the main repo due to time constraints, so [the fixes in it](https://github.com/seatgeek/mapbox-ios-sdk/commits/seatgeek) may not merge well.

**Comment by incanus** [comment]
@wprater Not sure if that's related. Is it while in compass tracking mode by chance? Because that uses a centered image view for the dot instead of a real annotation. Perhaps it's got some staleness issues with that method call. Could you maybe post a video of what you're seeing? You can simulate user tracking in Xcode to do this on the simulator. 

@sobri909 Ok. I'll leave this open until such time as we can get to the (stable) bottom of things.

**Comment by wprater** [comment]
@incanus Im not using tracking mode with heading, only setting the `showsUserLocation` to `true`.  I had it set on a custom location in the simulator, but setting it to freeway mode does help me indicate that it is indeed the actual user annotation.  It will appear right in the middle after my zoom event, but when the location changes (the freeway drive), it will zoom off really quick.

I can send you a video in private if that would help.

**Comment by incanus** [comment]
@wprater  To clarify, is your issue seen with this fix applied or in a normal branch? I should have been clear about that earlier. If it's not related to this issue, please create a new ticket for it. 

Meanwhile, still leaving this ticket open until @sobri909 is able to adapt this pull or confirm that we can just close it.

**Comment by wprater** [comment]
@incanus it's in the normal branch.  I'll open a ticket

**Pull request closed without merging**
