### PR TITLE
Supporting conditional tile downloads

### PR DESCRIPTION
**Pull request by rgal75**
It would be good to be able to allow/disallow tile downloads from client code.  

**Example use-case**
Let's suppose that the application has a requirement to allow any network traffic ONLY when the phone has WiFi coverage. On 3G, it can only send data if the user explicitly allows it via a setting.
Currently, MapBox downloads map tiles whenever it can and this behaviour cannot be managed by the client. 

This feature would give the client the possibility to implement a condition (in the form of a block) that allows/disallows tile downloads.

### CODE REVIEW

**Comment by rgal75** [comment]
I just noticed that my Pull Request contains 40 commits. Actually, it was intended to contain only one: a42edcd

Sorry for this, I am new to Git and GitHub and I will be more careful in the future.

**Comment by incanus** [comment]
Assigned to [Tender discussion #1151](http://support.mapbox.com/discussions/mapbox-ios-sdk/1151-conditional-tile-downloads).

**Comment by lightandshadow68** [comment]
Is there an update on this? The Tender discussion indicates the issue is closed, but I'm unable to find the commit in the current SDK.

**Comment by incanus** [comment]
Thanks for this submission, but I think it would be better served in the general case by subclassing the tile source in question (e.g. `RMMapboxSource`) to add in these sorts of checks instead of adding more API overhead (albeit light) for everyone.

**Pull request closed without merging**
