### PR TITLE
add WMS support

### PR DESCRIPTION
**Pull request by halset**
Long time ago, I added a RMWMSSource to /route-me/route-me. This is the same thing but with some minor changes from my project + some changes to confirm with the mapbox fork.

 Example (from RMWMSSource.h):
 RMWMS *wms = [[RMWMS alloc] init];
 wms.urlPrefix = @"http://vmap0.tiles.osgeo.org/wms/vmap0";
 wms.layers = @"basic";
 RMWMSSource *wmsSource = [[RMWMSSource alloc] init];
 wmsSource.wms = wms;
 wmsSource.uniqueTilecacheKey = @"abc";
 [mapView setTileSource:wmsSource];

### CODE REVIEW

**Comment by halset** [comment]
@incanus, can you take a look at this?

**Comment by incanus** [comment]
Will try to. YOu could also submit directly to https://github.com/Alpstein/route-me for possibly faster results, but I will try to check this out :-)

**Comment by halset** [comment]
Thanks, @incanus . I have added it to Alpstein as well - https://github.com/Alpstein/route-me/pull/133

**Comment by halset** [comment]
The Alpstein pull request is merged. Will you merge over the WMS stuff from Alpstein @incanus ? If so, I guess this pull request can be closed.

**Comment by incanus** [comment]
Yep, will be watching. I've got a [big pull request](https://github.com/Alpstein/route-me/pull/131) that I'm waiting on first.

**Comment by incanus** [comment]
I'll close here, as I'll take this down from Alpstein as soon as I can per normal dev cycle.

**Pull request closed without merging**
